spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: root
    password: lvh130902
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: lvh
    password: lvh
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: c546dfe71fe6a1a11609a3ca0394f6d6ef0f9105644a881390c7f2fcf29cfcb1
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088